name: Sync Fork

on:
  schedule:
    - cron: '* * * * *' # every minute
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          token: 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
          owner: mrios
          base: main
          head: main
