name: Pull Request Fork

on:
  schedule:
    - cron: '*/60 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          token: ${{ secrets.TOKEN }}
          owner: test-branching
          base: main
          head: main
          auto_merge: false
          retries: 1
          retry_after: 5
          auto_approve: false
